### ISSUE TITLE
Assignment 1-1 - The Basics

### ISSUE THREAD

**Issue by gstark** [byronroark/assignments#1]
- [x] Read Mason's [Code School Manefesto](http://masondesu.github.io/code-school-manifesto/).
- [x] Look over this [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide). You don't need to commit it all to memory. You probably won't understand all of it; that's okay. Just skim it, know that it exists, bookmark it, and refer to it often as we move forward.
- [x] Complete the just the exercises given below by copying the comments to a new file (name it `day_one.rb`) and placing your solution below each comment.
- [x] Publish your completed exercises to a Github Gist
  - HINT: Use the same filename in the "Filename with extension" input box.
- [x] Add the link to the Github Gist to a comment in this issue
- [x] Close the issue to indicate you are complete
- **Bonus**
  - [x] Clone the Gist you created to your computer.
  - [x] Add the bonus exercises to your `day_one.rb` and attempt to complete them both.
  - [x] Install `zsh` and `oh-my-zsh` and choose a theme of your liking. Take a screenshot of your terminal with the theme installed. Attach to the issue before closing.
  - [x] Customize the color of your terminal background and font color. Take a screenshot of your terminal with your color selection. Attach to the issue before closing.
- [x] Close this issue to notify me for review.

`day_one.rb`:

``` ruby
#1. Assign "Hello World" to a variable named message.

#2. Assign a different string to a different variable.

#3. Assign a number to a variable.

#4. Make an array of at least four of your favorite movies or books or bands.

#5. Make a hash of information about yourself with at least four key-value pairs.
```
### Bonus Exercises

``` ruby
#6. Use string interpolation to display the number from exercise 3 in the middle a string.

#7. Make an array of hashes containing more information about your favorite movies. The hashes should have at least three key value pairs.

#8. Use `each` to loop through the answer from exercise #7 and print only one property from the hash. i.e., given `{ title: "Gone with the Wind" }` you print "Gone with the Wind".
```
### Resources
- Creating gists - https://help.github.com/articles/creating-gists/
- Try out your code first in `irb`
- Ask questions. Talk to other students first, then come ask in pairs!

**Comment by chadoak4** [comment]
https://gist.github.com/chadoak4/278d5628c75fb0ebb060

**Comment by byronroark** [comment]
<img width="887" alt="screen shot of customized zsh terminal" src="https://cloud.githubusercontent.com/assets/9055067/9455355/793c8a5a-4a98-11e5-9d3b-1ccb4bdafb48.png">

**Comment by byronroark** [comment]
https://gist.github.com/byronroark/caa3a2e2d64a566818d2

**Comment by byronroark** [comment]
<img width="883" alt="screen shot of changed font color" src="https://cloud.githubusercontent.com/assets/9055067/9455499/daa3be20-4a99-11e5-88fb-9cd592507724.png">

**Comment by byronroark** [comment]
Cloned gist to local

**Comment by gstark** [comment]
Great stuff! If you feel like it, work on completing task 8 for more stretch.

**Comment by gstark** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/55jOowTAknOXC/200w_d.gif)

**Comment by byronroark** [comment]
Lesson 8 each loop complete!
https://gist.github.com/byronroark/caa3a2e2d64a566818d2
