### ISSUE TITLE
Assignment 5-1 - Green Eggs and Ham

### ISSUE THREAD

**Issue by gstark** [byronroark/assignments#16]
## Enumerable Practice

This assignment practices what we learned about `Enumerable` -- We continue to use various `enumerable` methods such as `all?` and `any?` in our recent homework. This practice reinforces some of the other enumerables available to us.

_Explorer Mode_
- Go to this URL https://github.com/tiy-tpa-ruby-q3-2015/green_eggs_and_ham
- [x] _Fork_ the repo using the github web ui (click on the FORK icon in the upper right)
- [x] _clone_ the repository to your computer. Ensure you are in the main directory where you keep your various projects (e.g. `~/tiy`) and are _NOT_ inside another homework assignment's directory.
- [x] Follow the directions in the readme (which you can see on the github page as well)

_Adventure Mode_
- [x] Write a test to validate how many punctuation marks are in the text. Write the _TEST_ into the test_green_eggs_and_ham.rb _first_ -- you will have to manually count the punctuation. Then write a test to expect that as the result of a method called `punctuation_count` defined in the class in `green_eggs_and_ham.rb`
- [x] Write a test to validate the line that is in the file the most often. (excluding blanks) -- Figure out _yourself_ which line this is. Then write a test to expect that as the result of a method called `punctuation_count` defined in the class in `green_eggs_and_ham.rb`

**Comment by byronroark** [comment]
Awesome exercise! All tests passing and completed adventure mode.
https://github.com/byronroark/green_eggs_and_ham

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/5tcvZn3xsLgXe/200w_d.gif)
