### ISSUE TITLE
Assignment 5-2 - Databasics

### ISSUE THREAD

**Issue by gstark** [byronroark/assignments#17]
Fork the repository below and follow the instructions in the included README.md

[https://github.com/tiy-tpa-ruby-q3-2015/databasics](https://github.com/tiy-tpa-ruby-q3-2015/databasics)

**Comment by byronroark** [comment]
https://github.com/byronroark/databasics

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/55jOowTAknOXC/200w_d.gif)
