### ISSUE TITLE
Assignment 7-2 - Secure (kinda) Rails Dictionary

### ISSUE THREAD

**Issue by gstark** [byronroark/assignments#25]
You did a great job on testing the Rails Dictionary for Webster's.

However the CEO noted that just about anyone on the internet can add a new word to the system. If you've spent any time on the internet you know what havoc this can bring.

Your task now is to add a simple authentication system to the Webster's dictionary app.
# Explorer Mode
- [x] Create a users model with an `email` and `password` field
- [x] Seed the following accounts:
     `gavin@example.com/sekret`
     `jason@example.com/alsosekret`
     `toni@example.com/supersekret`
- [x] Using the session-as-a-resource style from today's lecture create the ability to login and logout of your dictionary app
- [x] Make the login page styled as nicely as the rest of your app
- [x] Make it so that you cannot access any of the dictionary features unless you are logged in
- [x] Did this cause any of your tests to fail?
- [x] Deploy your application to Heroku and see that the login works (remember you may need to `heroku run rake db:seed` to get the seed accounts required above to be loaded)
# Adventure Mode
- [x] Fix any tests that started to fail due to authentication.
- [x] Change the system so that you can see the list of definitions and search even if you are not logged in.
- [x] Creating/deleting/showing a definition should still require a login
# Epic Mode
- [x] Integrate [devise](http://devise.plataformatec.com.br/) into your app and throw away our custom (and not so great) authentication system.
- [x] See how many features (sign up, password reminder, remember me, etc.) from devise's list of configurable behaviors you feel like integrating.
- [x] Deploy this to Heroku and have some friends sign up and define some words!

**Comment by byronroark** [comment]
Repo link with commits demonstrating custom login converting to devise:
https://github.com/byronroark/dictionary
Deployed to Heroku! 
http://floating-cove-9534.herokuapp.com
...finishing last test for search

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/QPHDRnGgHqGTC/200w_d.gif)
