### ISSUE TITLE
Assignment 8-1 - Continue Iron Topics

### ISSUE THREAD

**Issue by gstark** [byronroark/assignments#28]
Complete Iron Topics while looking at the in-class code from week8/day-1

Close this issue when you have closed the weekend lab issue.

**Comment by byronroark** [comment]
http://byron-topics.herokuapp.com/

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/4PZXI3LdlpBWU/200w_d.gif)
