### ISSUE TITLE
Assignment 9-1 - Getting started on an existing app

### ISSUE THREAD

**Issue by gstark** [byronroark/assignments#32]
Your first tasks as a new developer on a team will be to work on features/functions of an _existing_ app. Getting used to working with _other people's code_ is a valuable skill.

Today in class we experienced the difficulty that happens when getting a new project running on our laptops.

Our homework for the next few days is to work on issues in this repository.
# Homework

Over the next few days we will work on improving this `Hours` app. Each of you will work on, and close, at least one issue in the repository. Your code will be submitted via a Pull Request and we will review and discuss the code in class before merging.

A team leader will be selected to assign the issues and perform the merging of pull requests.
- [x] Discuss, in `tpa_aug2015_rails` who will be your team leader. Let me know, in the slack room, who your team leader is. The team leader will have the following responsibilities:
  - [x] Assign issues to team-mates
  - [x] Merge all pull requests
  - [x] Create new issues if needed
- [x] Read all of the issues in the repository to make your case to the team leader if there are issues you would prefer
- [x] Browse through the code to get a sense of how the project works. There will be code you don't understand, this is expected. If there is code, syntax, or features you don't understand, make a list and we will cover them in class tomorrow.
# Final project work

We will be having "Pitch Day" on Thursday, so we need to have our final project ideas ready to discuss.
- [ ] Prepare a short description of your final project idea. Try to have a primary and a backup idea ready.
- [x] Determine if you want to work on a solo project or a team project.
- [ ] If you want to work on a team project come to me with your team and idea.

**Comment by byronroark** [comment]
Pull request for Issue 11 completed. Closing this issue.
