### ISSUE TITLE
Assignment 2-1 - HTML/CSS Basics

### ISSUE THREAD

**Issue by gstark** [byronroark/assignments#5]
- [x] Read [this article](http://blog.froont.com/brief-history-of-web-design-for-designers/) on the history of web design.
- [x] Compose a short (a few paragraphs) blog that summarizes your thoughts on the web; where's it's been an where it's going.
- [x] Create an HTML document that contains your blog. It should have a title, a byline and the article itself.
### Explorer Mode
- [x] Mark up your document with valid HTML.
- [x] Use at least 12 different HTML tags.
- [x] Add at least one image to your page.
- [x] Use valid CSS to style the page.
- [x] Research the `id` and `class` HTML attributes.
- [x] Use at least 12 CSS statements to style the page (a statement includes a selector and a number of properties). Try to use `id` and `class` attributes in your CSS selectors where relevant.
- [x] All of your HTML and CSS should be formatted cleanly and consistently.

**Note:** Adventure and Epic Modes will be published later today.
## Additional Resources
- https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags
- http://atozcss.com/start-here/
- http://www.evolutionoftheweb.com

**Comment by byronroark** [comment]
https://github.com/byronroark/html_basics_blog.git

**Comment by gstark** [comment]
Looks good!

I think you are missing an image from your repo when I view it myself. Chances are the file is in your working directory but not pushed to github.

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/Vg7eQxnFuphPG/200w_d.gif)
